-- oxy:deploy-phase=post
-- Default public job sources. Each is a keyless aggregator or board; their
-- listings also seed the employers' own ATS boards through discovery. A row an
-- operator already registered or disabled is left exactly as it is.
INSERT INTO "clarity_job_feeds" ("id", "kind", "identifier", "label") VALUES
  (gen_random_uuid()::text, 'remoteok', 'remoteok', 'RemoteOK'),
  (gen_random_uuid()::text, 'arbeitnow', 'arbeitnow', 'Arbeitnow'),
  (gen_random_uuid()::text, 'aidevboard', 'aidevboard', 'AI Dev Jobs'),
  (gen_random_uuid()::text, 'jobicy', 'jobicy', 'Jobicy'),
  (gen_random_uuid()::text, 'workingnomads', 'workingnomads', 'Working Nomads'),
  (gen_random_uuid()::text, 'weworkremotely', 'weworkremotely', 'We Work Remotely'),
  (gen_random_uuid()::text, 'artificialintelligencejobs', 'artificialintelligencejobs', 'artificialintelligencejobs.co'),
  (gen_random_uuid()::text, 'fourdayweek', 'fourdayweek', '4dayweek.io'),
  (gen_random_uuid()::text, 'jobtech', 'jobtech', 'Arbetsförmedlingen JobTech'),
  (gen_random_uuid()::text, 'devitjobs', 'devitjobs.uk', 'DevITjobs UK'),
  (gen_random_uuid()::text, 'devitjobs', 'devitjobs.com', 'DevITjobs US'),
  (gen_random_uuid()::text, 'devitjobs', 'germantechjobs.de', 'GermanTechJobs'),
  (gen_random_uuid()::text, 'devitjobs', 'swissdevjobs.ch', 'SwissDevJobs'),
  (gen_random_uuid()::text, 'devitjobs', 'devitjobs.nl', 'DevITjobs NL'),
  (gen_random_uuid()::text, 'freehire', 'freehire', 'freehire'),
  (gen_random_uuid()::text, 'freehire', 'source=greenhouse', 'freehire · Greenhouse'),
  (gen_random_uuid()::text, 'freehire', 'source=lever', 'freehire · Lever'),
  (gen_random_uuid()::text, 'freehire', 'source=ashby', 'freehire · Ashby'),
  (gen_random_uuid()::text, 'freehire', 'source=workday', 'freehire · Workday'),
  (gen_random_uuid()::text, 'freehire', 'source=personio', 'freehire · Personio'),
  (gen_random_uuid()::text, 'freehire', 'source=recruitee', 'freehire · Recruitee'),
  (gen_random_uuid()::text, 'freehire', 'source=bamboohr', 'freehire · BambooHR'),
  (gen_random_uuid()::text, 'freehire', 'source=rippling', 'freehire · Rippling'),
  (gen_random_uuid()::text, 'freehire', 'source=breezy', 'freehire · Breezy'),
  (gen_random_uuid()::text, 'freehire', 'source=pinpoint', 'freehire · Pinpoint'),
  (gen_random_uuid()::text, 'freehire', 'source=workable', 'freehire · Workable'),
  (gen_random_uuid()::text, 'eures', 'at11', 'EURES · Austria AT11'),
  (gen_random_uuid()::text, 'eures', 'at12', 'EURES · Austria AT12'),
  (gen_random_uuid()::text, 'eures', 'at13', 'EURES · Austria AT13'),
  (gen_random_uuid()::text, 'eures', 'at21', 'EURES · Austria AT21'),
  (gen_random_uuid()::text, 'eures', 'at22', 'EURES · Austria AT22'),
  (gen_random_uuid()::text, 'eures', 'at31', 'EURES · Austria AT31'),
  (gen_random_uuid()::text, 'eures', 'at32', 'EURES · Austria AT32'),
  (gen_random_uuid()::text, 'eures', 'at33', 'EURES · Austria AT33'),
  (gen_random_uuid()::text, 'eures', 'at34', 'EURES · Austria AT34'),
  (gen_random_uuid()::text, 'eures', 'be1', 'EURES · Belgium BE1'),
  (gen_random_uuid()::text, 'eures', 'be2', 'EURES · Belgium BE2'),
  (gen_random_uuid()::text, 'eures', 'be3', 'EURES · Belgium BE3'),
  (gen_random_uuid()::text, 'eures', 'bg31', 'EURES · Bulgaria BG31'),
  (gen_random_uuid()::text, 'eures', 'bg32', 'EURES · Bulgaria BG32'),
  (gen_random_uuid()::text, 'eures', 'bg33', 'EURES · Bulgaria BG33'),
  (gen_random_uuid()::text, 'eures', 'bg34', 'EURES · Bulgaria BG34'),
  (gen_random_uuid()::text, 'eures', 'bg41', 'EURES · Bulgaria BG41'),
  (gen_random_uuid()::text, 'eures', 'bg42', 'EURES · Bulgaria BG42'),
  (gen_random_uuid()::text, 'eures', 'ch01', 'EURES · Switzerland CH01'),
  (gen_random_uuid()::text, 'eures', 'ch02', 'EURES · Switzerland CH02'),
  (gen_random_uuid()::text, 'eures', 'ch03', 'EURES · Switzerland CH03'),
  (gen_random_uuid()::text, 'eures', 'ch04', 'EURES · Switzerland CH04'),
  (gen_random_uuid()::text, 'eures', 'ch05', 'EURES · Switzerland CH05'),
  (gen_random_uuid()::text, 'eures', 'ch06', 'EURES · Switzerland CH06'),
  (gen_random_uuid()::text, 'eures', 'ch07', 'EURES · Switzerland CH07'),
  (gen_random_uuid()::text, 'eures', 'cy', 'EURES · Cyprus'),
  (gen_random_uuid()::text, 'eures', 'cz010', 'EURES · Czechia CZ010'),
  (gen_random_uuid()::text, 'eures', 'cz020', 'EURES · Czechia CZ020'),
  (gen_random_uuid()::text, 'eures', 'cz031', 'EURES · Czechia CZ031'),
  (gen_random_uuid()::text, 'eures', 'cz032', 'EURES · Czechia CZ032'),
  (gen_random_uuid()::text, 'eures', 'cz041', 'EURES · Czechia CZ041'),
  (gen_random_uuid()::text, 'eures', 'cz042', 'EURES · Czechia CZ042'),
  (gen_random_uuid()::text, 'eures', 'cz051', 'EURES · Czechia CZ051'),
  (gen_random_uuid()::text, 'eures', 'cz052', 'EURES · Czechia CZ052'),
  (gen_random_uuid()::text, 'eures', 'cz053', 'EURES · Czechia CZ053'),
  (gen_random_uuid()::text, 'eures', 'cz063', 'EURES · Czechia CZ063'),
  (gen_random_uuid()::text, 'eures', 'cz064', 'EURES · Czechia CZ064'),
  (gen_random_uuid()::text, 'eures', 'cz071', 'EURES · Czechia CZ071'),
  (gen_random_uuid()::text, 'eures', 'cz072', 'EURES · Czechia CZ072'),
  (gen_random_uuid()::text, 'eures', 'cz080', 'EURES · Czechia CZ080'),
  (gen_random_uuid()::text, 'eures', 'de1', 'EURES · Germany DE1'),
  (gen_random_uuid()::text, 'eures', 'de2', 'EURES · Germany DE2'),
  (gen_random_uuid()::text, 'eures', 'de3', 'EURES · Germany DE3'),
  (gen_random_uuid()::text, 'eures', 'de4', 'EURES · Germany DE4'),
  (gen_random_uuid()::text, 'eures', 'de5', 'EURES · Germany DE5'),
  (gen_random_uuid()::text, 'eures', 'de6', 'EURES · Germany DE6'),
  (gen_random_uuid()::text, 'eures', 'de7', 'EURES · Germany DE7'),
  (gen_random_uuid()::text, 'eures', 'de8', 'EURES · Germany DE8'),
  (gen_random_uuid()::text, 'eures', 'de9', 'EURES · Germany DE9'),
  (gen_random_uuid()::text, 'eures', 'dea', 'EURES · Germany DEA'),
  (gen_random_uuid()::text, 'eures', 'deb', 'EURES · Germany DEB'),
  (gen_random_uuid()::text, 'eures', 'dec', 'EURES · Germany DEC'),
  (gen_random_uuid()::text, 'eures', 'ded', 'EURES · Germany DED'),
  (gen_random_uuid()::text, 'eures', 'dee', 'EURES · Germany DEE'),
  (gen_random_uuid()::text, 'eures', 'def', 'EURES · Germany DEF'),
  (gen_random_uuid()::text, 'eures', 'deg', 'EURES · Germany DEG'),
  (gen_random_uuid()::text, 'eures', 'dk', 'EURES · Denmark'),
  (gen_random_uuid()::text, 'eures', 'ee', 'EURES · Estonia'),
  (gen_random_uuid()::text, 'eures', 'el', 'EURES · Greece'),
  (gen_random_uuid()::text, 'eures', 'es11', 'EURES · Spain ES11'),
  (gen_random_uuid()::text, 'eures', 'es12', 'EURES · Spain ES12'),
  (gen_random_uuid()::text, 'eures', 'es13', 'EURES · Spain ES13'),
  (gen_random_uuid()::text, 'eures', 'es21', 'EURES · Spain ES21'),
  (gen_random_uuid()::text, 'eures', 'es22', 'EURES · Spain ES22'),
  (gen_random_uuid()::text, 'eures', 'es23', 'EURES · Spain ES23'),
  (gen_random_uuid()::text, 'eures', 'es24', 'EURES · Spain ES24'),
  (gen_random_uuid()::text, 'eures', 'es30', 'EURES · Spain ES30'),
  (gen_random_uuid()::text, 'eures', 'es41', 'EURES · Spain ES41'),
  (gen_random_uuid()::text, 'eures', 'es42', 'EURES · Spain ES42'),
  (gen_random_uuid()::text, 'eures', 'es43', 'EURES · Spain ES43'),
  (gen_random_uuid()::text, 'eures', 'es51', 'EURES · Spain ES51'),
  (gen_random_uuid()::text, 'eures', 'es52', 'EURES · Spain ES52'),
  (gen_random_uuid()::text, 'eures', 'es53', 'EURES · Spain ES53'),
  (gen_random_uuid()::text, 'eures', 'es61', 'EURES · Spain ES61'),
  (gen_random_uuid()::text, 'eures', 'es62', 'EURES · Spain ES62'),
  (gen_random_uuid()::text, 'eures', 'es63', 'EURES · Spain ES63'),
  (gen_random_uuid()::text, 'eures', 'es64', 'EURES · Spain ES64'),
  (gen_random_uuid()::text, 'eures', 'es70', 'EURES · Spain ES70'),
  (gen_random_uuid()::text, 'eures', 'fi196', 'EURES · Finland FI196'),
  (gen_random_uuid()::text, 'eures', 'fi198', 'EURES · Finland FI198'),
  (gen_random_uuid()::text, 'eures', 'fi199', 'EURES · Finland FI199'),
  (gen_random_uuid()::text, 'eures', 'fi19a', 'EURES · Finland FI19A'),
  (gen_random_uuid()::text, 'eures', 'fi19b', 'EURES · Finland FI19B'),
  (gen_random_uuid()::text, 'eures', 'fi1b1', 'EURES · Finland FI1B1'),
  (gen_random_uuid()::text, 'eures', 'fi1c1', 'EURES · Finland FI1C1'),
  (gen_random_uuid()::text, 'eures', 'fi1c2', 'EURES · Finland FI1C2'),
  (gen_random_uuid()::text, 'eures', 'fi1c5', 'EURES · Finland FI1C5'),
  (gen_random_uuid()::text, 'eures', 'fi1c6', 'EURES · Finland FI1C6'),
  (gen_random_uuid()::text, 'eures', 'fi1c7', 'EURES · Finland FI1C7'),
  (gen_random_uuid()::text, 'eures', 'fi1d5', 'EURES · Finland FI1D5'),
  (gen_random_uuid()::text, 'eures', 'fi1d7', 'EURES · Finland FI1D7'),
  (gen_random_uuid()::text, 'eures', 'fi1d8', 'EURES · Finland FI1D8'),
  (gen_random_uuid()::text, 'eures', 'fi1d9', 'EURES · Finland FI1D9'),
  (gen_random_uuid()::text, 'eures', 'fi1da', 'EURES · Finland FI1DA'),
  (gen_random_uuid()::text, 'eures', 'fi1db', 'EURES · Finland FI1DB'),
  (gen_random_uuid()::text, 'eures', 'fi1dc', 'EURES · Finland FI1DC'),
  (gen_random_uuid()::text, 'eures', 'fi200', 'EURES · Finland FI200'),
  (gen_random_uuid()::text, 'eures', 'fr10', 'EURES · France FR10'),
  (gen_random_uuid()::text, 'eures', 'frb0', 'EURES · France FRB0'),
  (gen_random_uuid()::text, 'eures', 'frc1', 'EURES · France FRC1'),
  (gen_random_uuid()::text, 'eures', 'frc2', 'EURES · France FRC2'),
  (gen_random_uuid()::text, 'eures', 'frd1', 'EURES · France FRD1'),
  (gen_random_uuid()::text, 'eures', 'frd2', 'EURES · France FRD2'),
  (gen_random_uuid()::text, 'eures', 'fre1', 'EURES · France FRE1'),
  (gen_random_uuid()::text, 'eures', 'fre2', 'EURES · France FRE2'),
  (gen_random_uuid()::text, 'eures', 'frf1', 'EURES · France FRF1'),
  (gen_random_uuid()::text, 'eures', 'frf2', 'EURES · France FRF2'),
  (gen_random_uuid()::text, 'eures', 'frf3', 'EURES · France FRF3'),
  (gen_random_uuid()::text, 'eures', 'frg0', 'EURES · France FRG0'),
  (gen_random_uuid()::text, 'eures', 'frh0', 'EURES · France FRH0'),
  (gen_random_uuid()::text, 'eures', 'fri1', 'EURES · France FRI1'),
  (gen_random_uuid()::text, 'eures', 'fri2', 'EURES · France FRI2'),
  (gen_random_uuid()::text, 'eures', 'fri3', 'EURES · France FRI3'),
  (gen_random_uuid()::text, 'eures', 'frj1', 'EURES · France FRJ1'),
  (gen_random_uuid()::text, 'eures', 'frj2', 'EURES · France FRJ2'),
  (gen_random_uuid()::text, 'eures', 'frk1', 'EURES · France FRK1'),
  (gen_random_uuid()::text, 'eures', 'frk2', 'EURES · France FRK2'),
  (gen_random_uuid()::text, 'eures', 'frl0', 'EURES · France FRL0'),
  (gen_random_uuid()::text, 'eures', 'frm0', 'EURES · France FRM0'),
  (gen_random_uuid()::text, 'eures', 'fry1', 'EURES · France FRY1'),
  (gen_random_uuid()::text, 'eures', 'fry2', 'EURES · France FRY2'),
  (gen_random_uuid()::text, 'eures', 'fry3', 'EURES · France FRY3'),
  (gen_random_uuid()::text, 'eures', 'fry4', 'EURES · France FRY4'),
  (gen_random_uuid()::text, 'eures', 'fry5', 'EURES · France FRY5'),
  (gen_random_uuid()::text, 'eures', 'hr', 'EURES · Croatia'),
  (gen_random_uuid()::text, 'eures', 'hu', 'EURES · Hungary'),
  (gen_random_uuid()::text, 'eures', 'ie', 'EURES · Ireland'),
  (gen_random_uuid()::text, 'eures', 'is', 'EURES · Iceland'),
  (gen_random_uuid()::text, 'eures', 'it', 'EURES · Italy'),
  (gen_random_uuid()::text, 'eures', 'li', 'EURES · Liechtenstein'),
  (gen_random_uuid()::text, 'eures', 'lt', 'EURES · Lithuania'),
  (gen_random_uuid()::text, 'eures', 'lu', 'EURES · Luxembourg'),
  (gen_random_uuid()::text, 'eures', 'lv', 'EURES · Latvia'),
  (gen_random_uuid()::text, 'eures', 'mt', 'EURES · Malta'),
  (gen_random_uuid()::text, 'eures', 'nl11', 'EURES · Netherlands NL11'),
  (gen_random_uuid()::text, 'eures', 'nl12', 'EURES · Netherlands NL12'),
  (gen_random_uuid()::text, 'eures', 'nl13', 'EURES · Netherlands NL13'),
  (gen_random_uuid()::text, 'eures', 'nl21', 'EURES · Netherlands NL21'),
  (gen_random_uuid()::text, 'eures', 'nl22', 'EURES · Netherlands NL22'),
  (gen_random_uuid()::text, 'eures', 'nl23', 'EURES · Netherlands NL23'),
  (gen_random_uuid()::text, 'eures', 'nl32', 'EURES · Netherlands NL32'),
  (gen_random_uuid()::text, 'eures', 'nl34', 'EURES · Netherlands NL34'),
  (gen_random_uuid()::text, 'eures', 'nl35', 'EURES · Netherlands NL35'),
  (gen_random_uuid()::text, 'eures', 'nl36', 'EURES · Netherlands NL36'),
  (gen_random_uuid()::text, 'eures', 'nl41', 'EURES · Netherlands NL41'),
  (gen_random_uuid()::text, 'eures', 'nl42', 'EURES · Netherlands NL42'),
  (gen_random_uuid()::text, 'eures', 'no02', 'EURES · Norway NO02'),
  (gen_random_uuid()::text, 'eures', 'no06', 'EURES · Norway NO06'),
  (gen_random_uuid()::text, 'eures', 'no07', 'EURES · Norway NO07'),
  (gen_random_uuid()::text, 'eures', 'no08', 'EURES · Norway NO08'),
  (gen_random_uuid()::text, 'eures', 'no09', 'EURES · Norway NO09'),
  (gen_random_uuid()::text, 'eures', 'no0a', 'EURES · Norway NO0A'),
  (gen_random_uuid()::text, 'eures', 'no0b', 'EURES · Norway NO0B'),
  (gen_random_uuid()::text, 'eures', 'pl21', 'EURES · Poland PL21'),
  (gen_random_uuid()::text, 'eures', 'pl22', 'EURES · Poland PL22'),
  (gen_random_uuid()::text, 'eures', 'pl41', 'EURES · Poland PL41'),
  (gen_random_uuid()::text, 'eures', 'pl42', 'EURES · Poland PL42'),
  (gen_random_uuid()::text, 'eures', 'pl43', 'EURES · Poland PL43'),
  (gen_random_uuid()::text, 'eures', 'pl51', 'EURES · Poland PL51'),
  (gen_random_uuid()::text, 'eures', 'pl52', 'EURES · Poland PL52'),
  (gen_random_uuid()::text, 'eures', 'pl61', 'EURES · Poland PL61'),
  (gen_random_uuid()::text, 'eures', 'pl62', 'EURES · Poland PL62'),
  (gen_random_uuid()::text, 'eures', 'pl63', 'EURES · Poland PL63'),
  (gen_random_uuid()::text, 'eures', 'pl71', 'EURES · Poland PL71'),
  (gen_random_uuid()::text, 'eures', 'pl72', 'EURES · Poland PL72'),
  (gen_random_uuid()::text, 'eures', 'pl81', 'EURES · Poland PL81'),
  (gen_random_uuid()::text, 'eures', 'pl82', 'EURES · Poland PL82'),
  (gen_random_uuid()::text, 'eures', 'pl84', 'EURES · Poland PL84'),
  (gen_random_uuid()::text, 'eures', 'pl92', 'EURES · Poland PL92'),
  (gen_random_uuid()::text, 'eures', 'pt', 'EURES · Portugal'),
  (gen_random_uuid()::text, 'eures', 'ro', 'EURES · Romania'),
  (gen_random_uuid()::text, 'eures', 'se110', 'EURES · Sweden SE110'),
  (gen_random_uuid()::text, 'eures', 'se121', 'EURES · Sweden SE121'),
  (gen_random_uuid()::text, 'eures', 'se122', 'EURES · Sweden SE122'),
  (gen_random_uuid()::text, 'eures', 'se123', 'EURES · Sweden SE123'),
  (gen_random_uuid()::text, 'eures', 'se124', 'EURES · Sweden SE124'),
  (gen_random_uuid()::text, 'eures', 'se125', 'EURES · Sweden SE125'),
  (gen_random_uuid()::text, 'eures', 'se211', 'EURES · Sweden SE211'),
  (gen_random_uuid()::text, 'eures', 'se212', 'EURES · Sweden SE212'),
  (gen_random_uuid()::text, 'eures', 'se213', 'EURES · Sweden SE213'),
  (gen_random_uuid()::text, 'eures', 'se214', 'EURES · Sweden SE214'),
  (gen_random_uuid()::text, 'eures', 'se221', 'EURES · Sweden SE221'),
  (gen_random_uuid()::text, 'eures', 'se224', 'EURES · Sweden SE224'),
  (gen_random_uuid()::text, 'eures', 'se231', 'EURES · Sweden SE231'),
  (gen_random_uuid()::text, 'eures', 'se232', 'EURES · Sweden SE232'),
  (gen_random_uuid()::text, 'eures', 'se311', 'EURES · Sweden SE311'),
  (gen_random_uuid()::text, 'eures', 'se312', 'EURES · Sweden SE312'),
  (gen_random_uuid()::text, 'eures', 'se313', 'EURES · Sweden SE313'),
  (gen_random_uuid()::text, 'eures', 'se321', 'EURES · Sweden SE321'),
  (gen_random_uuid()::text, 'eures', 'se322', 'EURES · Sweden SE322'),
  (gen_random_uuid()::text, 'eures', 'se331', 'EURES · Sweden SE331'),
  (gen_random_uuid()::text, 'eures', 'se332', 'EURES · Sweden SE332'),
  (gen_random_uuid()::text, 'eures', 'si', 'EURES · Slovenia'),
  (gen_random_uuid()::text, 'eures', 'sk01', 'EURES · Slovakia SK01'),
  (gen_random_uuid()::text, 'eures', 'sk02', 'EURES · Slovakia SK02'),
  (gen_random_uuid()::text, 'eures', 'sk03', 'EURES · Slovakia SK03'),
  (gen_random_uuid()::text, 'eures', 'sk04', 'EURES · Slovakia SK04'),
  (gen_random_uuid()::text, 'feinaactiva', 'feinaactiva', 'Feina Activa (SOC Catalunya)'),
  (gen_random_uuid()::text, 'karrierenrw', 'karrierenrw', 'Karriere.NRW'),
  (gen_random_uuid()::text, 'jobsadminch', 'jobsadminch', 'jobs.admin.ch'),
  (gen_random_uuid()::text, 'madgex', 'jobs.chronicle.com', 'The Chronicle of Higher Education Jobs'),
  (gen_random_uuid()::text, 'madgex', 'jobs.sciencecareers.org', 'Science Careers'),
  (gen_random_uuid()::text, 'madgex', 'jobs.theguardian.com', 'Guardian Jobs'),
  (gen_random_uuid()::text, 'rss_jsonld', 'https://djinni.co/jobs/rss/', 'Djinni'),
  (gen_random_uuid()::text, 'rss_jsonld', 'https://api.cryptojobslist.com/jobs.rss', 'Cryptojobslist'),
  (gen_random_uuid()::text, 'rss_jsonld', 'https://cryptocurrencyjobs.co/index.xml', 'cryptocurrencyjobs.co'),
  (gen_random_uuid()::text, 'rss_jsonld', 'https://dribbble.com/jobs.rss', 'Dribbble Jobs'),
  (gen_random_uuid()::text, 'sitemap', 'https://www.werkenvoornederland.nl/sitemap-vacatures.xml', 'Werken voor Nederland'),
  (gen_random_uuid()::text, 'sitemap', 'https://cityjobs.nyc.gov/vacanciessitemap.xml', 'NYC Jobs'),
  (gen_random_uuid()::text, 'sitemap', 'https://www.bne.gob.cl/sitemap.xml#/oferta/', 'Bolsa Nacional de Empleo (Chile)'),
  (gen_random_uuid()::text, 'sitemap', 'https://search.jobs.wa.gov.au/sitemap.xml#/jobs/', 'WA Government Jobs'),
  (gen_random_uuid()::text, 'oracle', 'jpmc.fa.oraclecloud.com/CX_1001', 'JPMorgan Chase'),
  (gen_random_uuid()::text, 'phenom', 'jobs.thermofisher.com/global/en', 'Thermo Fisher Scientific'),
  (gen_random_uuid()::text, 'eightfold', 'paypal.eightfold.ai/paypal.com', 'PayPal'),
  (gen_random_uuid()::text, 'eightfold', 'micron.eightfold.ai/micron.com', 'Micron'),
  (gen_random_uuid()::text, 'successfactors', 'jobs.schaeffler.com', 'Schaeffler'),
  (gen_random_uuid()::text, 'successfactors', 'careers.swissre.com', 'Swiss Re'),
  (gen_random_uuid()::text, 'jobvite', 'nutanix/qKr9VfwZ', 'Nutanix'),
  (gen_random_uuid()::text, 'jibe', 'careers.mcafee.com', 'McAfee'),
  (gen_random_uuid()::text, 'softgarden', 'johanniter', 'Johanniter'),
  (gen_random_uuid()::text, 'homerun', 'moneybird', 'Moneybird'),
  (gen_random_uuid()::text, 'hireology', 'vpmanagement', 'VP Management'),
  (gen_random_uuid()::text, 'getonboard', 'other', 'Get on Board · other'),
  (gen_random_uuid()::text, 'getonboard', 'advertising-media', 'Get on Board · advertising-media'),
  (gen_random_uuid()::text, 'getonboard', 'sysadmin-devops-qa', 'Get on Board · sysadmin-devops-qa'),
  (gen_random_uuid()::text, 'getonboard', 'education-coaching', 'Get on Board · education-coaching'),
  (gen_random_uuid()::text, 'getonboard', 'machine-learning-ai', 'Get on Board · machine-learning-ai'),
  (gen_random_uuid()::text, 'getonboard', 'operations-management', 'Get on Board · operations-management'),
  (gen_random_uuid()::text, 'getonboard', 'programming', 'Get on Board · programming'),
  (gen_random_uuid()::text, 'getonboard', 'customer-support', 'Get on Board · customer-support'),
  (gen_random_uuid()::text, 'getonboard', 'design-ux', 'Get on Board · design-ux'),
  (gen_random_uuid()::text, 'getonboard', 'technical-support', 'Get on Board · technical-support'),
  (gen_random_uuid()::text, 'getonboard', 'digital-marketing', 'Get on Board · digital-marketing'),
  (gen_random_uuid()::text, 'getonboard', 'sales', 'Get on Board · sales'),
  (gen_random_uuid()::text, 'getonboard', 'hardware-electronics', 'Get on Board · hardware-electronics'),
  (gen_random_uuid()::text, 'getonboard', 'cybersecurity', 'Get on Board · cybersecurity'),
  (gen_random_uuid()::text, 'getonboard', 'innovation-agile', 'Get on Board · innovation-agile'),
  (gen_random_uuid()::text, 'getonboard', 'mobile-developer', 'Get on Board · mobile-developer'),
  (gen_random_uuid()::text, 'getonboard', 'hr', 'Get on Board · hr'),
  (gen_random_uuid()::text, 'getonboard', 'data-science-analytics', 'Get on Board · data-science-analytics')
ON CONFLICT ("kind", "identifier") DO NOTHING;
