/**
 * Model Mappings Generator
 *
 * This utility generates complete model mappings with capabilities and pricing
 * IMPORTANT: Only use REAL, currently available model IDs
 */

import type { ModelMapping, ClarityTier } from './clarity-models';
import { getModelCapabilities, getModelPricing } from './model-capabilities-data';

// Helper to create a model mapping with all required fields
export function createMapping(
  provider: string,
  modelId: string,
  priority: number,
  qualityScore: number
): ModelMapping {
  const pricing = getModelPricing(modelId);
  const capabilities = getModelCapabilities(modelId);

  return {
    provider,
    modelId,
    priority,
    qualityScore,
    pricingTier: pricing.tier,
    costPer1MInput: pricing.costPer1MInput,
    costPer1MOutput: pricing.costPer1MOutput,
    averageLatencyMs: pricing.averageLatencyMs,
    capabilities,
  };
}

// Generate all tier mappings - ONLY REAL MODEL IDS
export const GENERATED_TIER_MAPPINGS: Partial<Record<ClarityTier, ModelMapping[]>> = {
  'lite': [
    createMapping('google', 'gemini-2.5-flash', 1, 75),
    createMapping('groq', 'llama-3.3-70b-versatile', 2, 65),
    createMapping('deepseek', 'deepseek-chat', 3, 72),
    createMapping('openai', 'gpt-4o-mini', 4, 68),
    createMapping('xai', 'grok-4-fast', 5, 70),
    createMapping('novita', 'meta-llama/llama-3.3-70b-instruct', 6, 60),
    createMapping('hyperbolic', 'deepseek-ai/DeepSeek-V3', 7, 64),
    createMapping('sambanova', 'Meta-Llama-3.3-70B-Instruct', 8, 62),
    createMapping('fireworks', 'accounts/fireworks/models/deepseek-v3', 9, 63),
    createMapping('replicate', 'meta/meta-llama-3.3-70b-instruct', 10, 63),
    createMapping('cohere', 'command-r7b-12-2024', 11, 60),
    createMapping('cerebras', 'llama-3.3-70b', 12, 62),
    createMapping('mistral', 'mistral-small-3.1-2503', 13, 58),
    createMapping('digitalocean', 'openai-gpt-5-nano', 14, 66),
    createMapping('digitalocean', 'llama3.3-70b-instruct', 15, 63),
    createMapping('digitalocean', 'openai-gpt-oss-20b', 16, 55),
  ],
  'v1': [
    createMapping('google', 'gemini-2.5-flash', 1, 88),
    createMapping('google', 'gemini-3-flash-preview', 2, 85),
    createMapping('deepseek', 'deepseek-chat', 3, 83),
    createMapping('xai', 'grok-4-fast', 4, 82),
    createMapping('groq', 'llama-3.3-70b-versatile', 5, 80),
    createMapping('openai', 'gpt-4o-mini', 6, 82),
    createMapping('fireworks', 'accounts/fireworks/models/deepseek-v3', 7, 79),
    createMapping('hyperbolic', 'deepseek-ai/DeepSeek-V3', 8, 77),
    createMapping('sambanova', 'Meta-Llama-3.3-70B-Instruct', 9, 76),
    createMapping('novita', 'meta-llama/llama-3.3-70b-instruct', 10, 74),
    createMapping('replicate', 'meta/meta-llama-3.3-70b-instruct', 11, 78),
    createMapping('cohere', 'command-r-08-2024', 12, 75),
    createMapping('cerebras', 'llama-3.3-70b', 13, 74),
    createMapping('mistral', 'mistral-small-3.1-2503', 14, 70),
    createMapping('digitalocean', 'openai-gpt-5-mini', 15, 80),
    createMapping('digitalocean', 'llama3.3-70b-instruct', 16, 72),
    createMapping('digitalocean', 'alibaba-qwen3-32b', 17, 70),
  ],
  'v1-codea': [
    createMapping('deepseek', 'deepseek-chat', 1, 94),
    createMapping('anthropic', 'claude-sonnet-4-20250514', 2, 95),
    createMapping('google', 'gemini-3-flash-preview', 3, 93),
    createMapping('xai', 'grok-4-fast', 4, 91),
    createMapping('groq', 'llama-3.3-70b-versatile', 5, 90),
    createMapping('google', 'gemini-2.5-pro', 6, 92),
    createMapping('openai', 'gpt-4o', 7, 91),
    createMapping('fireworks', 'accounts/fireworks/models/deepseek-v3', 8, 87),
    createMapping('replicate', 'meta/meta-llama-3.1-405b-instruct', 9, 88),
    createMapping('cohere', 'command-a-03-2025', 10, 86),
    createMapping('cerebras', 'llama-3.3-70b', 11, 82),
    createMapping('mistral', 'mistral-small-3.1-2503', 12, 78),
    createMapping('digitalocean', 'openai-gpt-5', 13, 90),
    createMapping('digitalocean', 'openai-gpt-5.1-codex-max', 14, 89),
  ],
  'v1-cowork': [
    createMapping('deepseek', 'deepseek-chat', 1, 93),
    createMapping('anthropic', 'claude-sonnet-4-20250514', 2, 95),
    createMapping('google', 'gemini-2.5-pro', 3, 92),
    createMapping('openai', 'gpt-4o', 4, 90),
    createMapping('xai', 'grok-4-fast', 5, 88),
    createMapping('groq', 'llama-3.3-70b-versatile', 6, 87),
    createMapping('replicate', 'meta/meta-llama-3.3-70b-instruct', 7, 85),
    createMapping('cohere', 'command-a-03-2025', 8, 83),
    createMapping('cerebras', 'llama-3.3-70b', 9, 80),
    createMapping('mistral', 'mistral-small-3.1-2503', 10, 76),
    createMapping('digitalocean', 'openai-gpt-5', 11, 88),
  ],
  'v1-browser': [
    createMapping('google', 'gemini-3-flash-preview', 1, 97),
    createMapping('anthropic', 'claude-sonnet-4-20250514', 2, 96),
    createMapping('google', 'gemini-2.5-pro', 3, 94),
    createMapping('perplexity', 'sonar-pro', 4, 93),
    createMapping('deepseek', 'deepseek-chat', 5, 92),
    createMapping('xai', 'grok-4-fast', 6, 89),
    createMapping('groq', 'llama-3.3-70b-versatile', 7, 89),
    createMapping('openai', 'gpt-4o', 8, 90),
    createMapping('replicate', 'meta/meta-llama-3.3-70b-instruct', 9, 87),
    createMapping('cloudflare', '@cf/meta/llama-3.2-11b-vision-instruct', 10, 86),
    createMapping('cerebras', 'llama-3.3-70b', 11, 82),
    createMapping('mistral', 'mistral-small-3.1-2503', 12, 78),
    createMapping('digitalocean', 'openai-gpt-5-mini', 13, 80),
  ],
  'v1-vision': [
    createMapping('google', 'gemini-3-flash-preview', 1, 97),
    createMapping('google', 'gemini-2.5-pro', 2, 96),
    createMapping('anthropic', 'claude-sonnet-4-20250514', 3, 95),
    createMapping('openai', 'gpt-4o', 4, 92),
    createMapping('xai', 'grok-4', 5, 90),
    createMapping('cloudflare', '@cf/meta/llama-3.2-11b-vision-instruct', 6, 88),
    createMapping('cohere', 'command-a-vision-07-2025', 7, 87),
    createMapping('digitalocean', 'openai-gpt-4o', 8, 90),
  ],
  'v1-audio': [
    createMapping('groq', 'whisper-large-v3-turbo', 1, 95),
    createMapping('groq', 'whisper-large-v3', 2, 93),
    createMapping('openai', 'whisper-1', 3, 92),
  ],
  'v1-tts': [
    createMapping('openai', 'tts-1', 1, 90),
    createMapping('openai', 'tts-1-hd', 2, 95),
    createMapping('openrouter', 'openai/tts-1', 3, 88),
    createMapping('digitalocean', 'fal-ai/elevenlabs/tts/multilingual-v2', 4, 87),
  ],
  'v1-image': [
    createMapping('openai', 'dall-e-3', 1, 92),
    createMapping('digitalocean', 'openai-gpt-image-1', 2, 90),
    createMapping('digitalocean', 'fal-ai/flux/schnell', 3, 85),
    createMapping('digitalocean', 'fal-ai/fast-sdxl', 4, 80),
  ],
  'v1-multimodal': [
    createMapping('google', 'gemini-3-pro-preview', 1, 99),
    createMapping('google', 'gemini-2.5-pro', 2, 98),
    createMapping('anthropic', 'claude-opus-4-20241120', 3, 97),
    createMapping('google', 'gemini-3-flash-preview', 4, 96),
    createMapping('openai', 'gpt-4o', 5, 95),
    createMapping('cloudflare', '@cf/meta/llama-3.2-11b-vision-instruct', 6, 90),
  ],
  'v1-pro': [
    createMapping('anthropic', 'claude-sonnet-4-20250514', 1, 96),
    createMapping('google', 'gemini-2.5-pro', 2, 95),
    createMapping('deepseek', 'deepseek-reasoner', 3, 94),
    createMapping('xai', 'grok-3', 4, 93),
    createMapping('openai', 'o1', 5, 92),
    createMapping('cohere', 'command-a-reasoning-08-2025', 6, 91),
    createMapping('perplexity', 'sonar-reasoning-pro', 7, 89),
    createMapping('digitalocean', 'anthropic-claude-4.6-sonnet', 8, 94),
    createMapping('digitalocean', 'openai-o3', 9, 92),
    createMapping('digitalocean', 'openai-gpt-5.2', 10, 90),
  ],
  'v1-pro-max': [
    createMapping('anthropic', 'claude-opus-4-20241120', 1, 98),
    createMapping('google', 'gemini-2.5-pro', 2, 96),
    createMapping('openai', 'o1', 3, 95),
    createMapping('xai', 'grok-4', 4, 94),
    createMapping('deepseek', 'deepseek-reasoner', 5, 94),
    createMapping('cohere', 'command-a-reasoning-08-2025', 6, 91),
    createMapping('digitalocean', 'anthropic-claude-opus-4.6', 7, 96),
    createMapping('digitalocean', 'openai-o1', 8, 93),
    createMapping('digitalocean', 'openai-gpt-5.2-pro', 9, 92),
  ],
  'v1-voice': [
    {
      provider: 'xai',
      modelId: 'grok-realtime',
      priority: 1,
      qualityScore: 85,
      pricingTier: 'paid' as const,
      costPerMinute: 0.05,
      capabilities: {
        voice: true,
        audio: true,
        video: false,
        vision: false,
        tools: true,
        codeExecution: false,
        webSearch: false,
        computerUse: false,
        streaming: true,
        systemPrompts: true,
        functionCalling: true,
        promptCaching: false,
        maxContextTokens: 32768,
        maxOutputTokens: 8192,
      },
    },
    {
      provider: 'openai',
      modelId: 'gpt-4o-realtime-preview',
      priority: 2,
      qualityScore: 90,
      pricingTier: 'paid' as const,
      costPerMinute: 0.06,
      capabilities: {
        voice: true,
        audio: true,
        video: false,
        vision: false,
        tools: true,
        codeExecution: false,
        webSearch: false,
        computerUse: false,
        streaming: true,
        systemPrompts: true,
        functionCalling: true,
        promptCaching: false,
        maxContextTokens: 128000,
        maxOutputTokens: 16384,
      },
    },
  ],
  'v1-voice-pro': [
    {
      provider: 'openai',
      modelId: 'gpt-4o-realtime-preview',
      priority: 1,
      qualityScore: 90,
      pricingTier: 'paid' as const,
      costPerMinute: 0.06,
      capabilities: {
        voice: true,
        audio: true,
        video: false,
        vision: false,
        tools: true,
        codeExecution: false,
        webSearch: false,
        computerUse: false,
        streaming: true,
        systemPrompts: true,
        functionCalling: true,
        promptCaching: false,
        maxContextTokens: 128000,
        maxOutputTokens: 16384,
      },
    },
    {
      provider: 'xai',
      modelId: 'grok-realtime',
      priority: 2,
      qualityScore: 85,
      pricingTier: 'paid' as const,
      costPerMinute: 0.05,
      capabilities: {
        voice: true,
        audio: true,
        video: false,
        vision: false,
        tools: true,
        codeExecution: false,
        webSearch: false,
        computerUse: false,
        streaming: true,
        systemPrompts: true,
        functionCalling: true,
        promptCaching: false,
        maxContextTokens: 32768,
        maxOutputTokens: 8192,
      },
    },
  ],
};
